### ISSUE TITLE
Camera.ImageArray Base64 Handoff Mode

### ISSUE THREAD

**Issue by fulsdavid** [ASCOMInitiative/alpyca#10]
First off, thank you so much for your work on this library! It is MUCH MUCH better than writing all the puts and gets out for a telescope control system.

I have one question about the camera module. Has the Base64 handoff mode been implemented when getting image arrays? I'm using this library with the Remote Server, and I believe this would make a difference in my overheads. 

Thank you!
-Carson

**Comment by BobDenny** [comment]
Hi Carson -- My apologies for not replying sooner. Base64 Handoff was one of the schemes that was being tried back in 2019, see [Alpaca ImageArray Performance Over Loopback](https://ascomtalk.groups.io/g/Developer/message/1167). This was eventually replaced with Peter Simpson's ImageBytes High Speed Image Transfer Protocol. See the latest [Alpaca API Reference V9 (May 2023 - PDF)](https://github.com/ASCOMInitiative/ASCOMRemote/raw/main/Documentation/ASCOM%20Alpaca%20API%20Reference.pdf) available at the [ASCOM Web Site Documentation Center.](https://ascom-standards.org/Documentation/Index.htm).  Alpyca handles this transparently, via detecting the HTTP `content-type` in the camera's image data that comes into Alpyca.  ASCOM Remote automatically converts the ASCOM COM ImageData to ImageBytes so a camera on a Windows system with a Windows ASCOM COM driver will automatically  benefit from ImageBytes. A native Alpaca camera driver would want to provide ImageBytes  not a JSON based blob. Alpyca will accept the JSON as well (again by `content-type`).  You can see this in action by looking in Camera.py, line 1569 or so, `_get_imagedata()`.
