### ISSUE TITLE
unexpected latency

### ISSUE THREAD

**Issue by deppenkaiser** [ASCOMInitiative/alpyca#2]
hello,

i have a Skywatcher AZ-EQ5 Pro and i use the USB serial interface to connect my mount with my pc.

when i send e. g. two commands:
	self._telescope.PulseGuide(GuideDirections.guideNorth, 100)
	self._telescope.PulseGuide(GuideDirections.guideEast, 100)

then it takes over 4 secs. to process them. my self written interface needs only a few ms to process it (same interfaces used: tcpip --> synscan --> usb --> mount).

so what's wrong?

**Comment by BobDenny** [comment]
We found that the library is not re-using sockets and instead opening a new port each time. I am getting ready to release 2.0.1rc1 with this fix, but for now you can use the attached device.py to keep all traffic on one socket. Of course remove the .txt and then replace it in the package. 
[device.py.txt](https://github.com/ASCOMInitiative/alpyca/files/9128271/device.py.txt)

**Comment by BobDenny** [comment]
I just released 2.0.1-rc1 ... just update to that.
