### ISSUE TITLE
DriverVersion returns a float???

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/alpyca#4]
DriverVersion has a type hint of 'str' but returns a float. This will raise an exception if the value from the driver cannot be coerced into a float.

The COM telescope simulator returns '6.6.0.0' as its DriverVersion. This is clearly incorrect, but other applications and APIs tolerate this.

I don't know who is correct, but the inconsistent behavior is frustrating.

It seems as though the Simulator needs to be corrected. Also, Conform needs to call out the illegal DriverVersion. I would suggest that Alpyca should not return a float,  simply pass the driver's returned value through to the client, as DriverAccess does.

**Comment by BobDenny** [comment]
Yep, fixed, It should actually return whatever string comes back. I used float() to enforce the n.m requirement but I agree with you that is a bad idea. Thanks Rick.
