### ISSUE TITLE
Unexpected behavior from Discovery

### ISSUE THREAD

**Issue by astroman133** [ASCOMInitiative/alpyca#6]
With the Omni Simulator running on my dev machine, discovery.search_ipv4() returns one server with an address of 127.0.0.1:32323, as expected. 

Now if I start ASCOM Remote, hosting the COM Telescope Simulator on the same PC, in addition to the Omni simulator. I still get a single server response from search_ipv4(). This response is 127.0.0.1:11111, which is correct for ASCOM Remote.

I expected to see both 127.0.0.1:32323 and 127.0.0.1:11111 in the servers list from the search_ipv4 call when both the Omni Simulator and ASCOM Remote are active and serving drivers.

**Comment by BobDenny** [comment]
Thanks for this, and in particular for the detailed repro scenario. I'll look at this ASAP this week.

**Comment by BobDenny** [comment]
Fixed. Needed to do multicast to 127.0.0.1 specifically (127.255.255.255). Tested on Windows and Linux. Thanks again for the good catch.
